version: '3.9'
services:
  # Node.js App
  server:
    build: . # Assumes you have a Dockerfile for your Node.js app
    container_name: node-app
    ports:
      - '3000:3000' # Expose your app port
    volumes:
      - ./:/app # Mount your code
      - server-node-modules:/app/node_modules # Persist node_modules
    environment:
      - DB_SERVER=sql-server # Use the service name as the host
      - DB_PORT=1433 # Default SQL Server port
      - DB_NAME=db_crud_usuarios
      - DB_USER=mateo
      - DB_PASSWORD=mateo123456
      - DB_ENCRYPT=false
      - DB_TRUST_SERVER_CERTIFICATE=true
    depends_on:
      - sql-server

  # SQL Server
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    ports:
      - '50779:1433' # Host:Container port (1433 is default for SQL Server)
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd # Change this!
      - MSSQL_PID=Express
    volumes:
      - sql-data:/var/opt/mssql # Persist database data

# Named volumes
volumes:
  server-node-modules:
  sql-data:
